# Generated by Django 5.1.6 on 2025-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
