# Generated by Django 5.1.6 on 2025-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_course_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_group",
            field=models.CharField(
                choices=[
                    ("Aptitude", "Aptitude"),
                    ("Soft Skill", "Soft Skill"),
                    ("Technical", "Technical"),
                ],
                default="Aptitude",
                max_length=20,
            ),
        ),
    ]
