# Generated by Django 5.1.6 on 2025-03-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_course_course_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="reason",
            field=models.TextField(
                blank=True, default="No explanation provided.", null=True
            ),
        ),
    ]
