# Generated by Django 5.1.6 on 2025-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=150)),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("ph_no", models.CharField(max_length=15)),
                ("reg_no", models.CharField(max_length=15, unique=True)),
                ("dep", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("clg_name", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
