# Generated by Django 5.1.7 on 2025-03-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("ph_no", models.CharField(max_length=15)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Aptitude", "Aptitude"),
                            ("Soft Skill", "Soft Skill"),
                            ("Technical", "Technical"),
                        ],
                        default="Technical",
                        max_length=50,
                    ),
                ),
                ("clg", models.CharField(max_length=150)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="trainer_profiles/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="training_pdfs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainer.trainer",
                    ),
                ),
            ],
        ),
    ]
