# Generated by Django 5.1.6 on 2025-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_sources_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="source_file",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
