# Generated by Django 5.1.6 on 2025-03-04 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_source_file_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source_file",
            name="file",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "docx"])
                ],
            ),
        ),
    ]
