# Generated by Django 5.1.7 on 2025-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_source_file_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clg_name", models.CharField(max_length=100, unique=True)),
                ("Source_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
