# Generated by Django 5.1.7 on 2025-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_clg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clg",
            name="Source_name",
        ),
        migrations.AddField(
            model_name="clg",
            name="course_name",
            field=models.CharField(
                choices=[
                    ("Aptitude", "Aptitude"),
                    ("SoftSkill", "Soft Skill"),
                    ("Technical", "Technical"),
                ],
                default="Aptitude",
                max_length=100,
            ),
        ),
    ]
